// Command toolsdoc generates TOOLS.md, a reference of every MCP tool exposed by
// the server, grouped by toolset. It boots the MCP server in-memory, lists the
// registered tools over an in-memory transport and renders the result as
// Markdown. Run it via `go generate ./...` or `make generate`.
package main

import (
	"context"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/rancher/rancher-ai-mcp/pkg/toolconfig"
	"github.com/rancher/rancher-ai-mcp/pkg/toolsets"
)

const outputFile = "TOOLS.md"

type toolInfo struct {
	name        string
	description string
	toolset     string
	write       bool
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "toolsdoc: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	ctx := context.Background()

	// Tools registered in read-only mode are the read-only tools. Any tool that
	// only appears in the full set is a write operation.
	readOnlyTools, err := listTools(ctx, toolconfig.Config{ReadOnly: true})
	if err != nil {
		return fmt.Errorf("listing read-only tools: %w", err)
	}
	readOnlyNames := make(map[string]struct{}, len(readOnlyTools))
	for _, t := range readOnlyTools {
		readOnlyNames[t.Name] = struct{}{}
	}

	allTools, err := listTools(ctx, toolconfig.Config{EnableExec: true})
	if err != nil {
		return fmt.Errorf("listing all tools: %w", err)
	}

	infos := make([]toolInfo, 0, len(allTools))
	for _, t := range allTools {
		_, readOnly := readOnlyNames[t.Name]
		infos = append(infos, toolInfo{
			name:        t.Name,
			description: t.Description,
			toolset:     toolsetOf(t),
			write:       !readOnly,
		})
	}

	doc := render(infos)
	if err := os.WriteFile(outputFile, []byte(doc), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", outputFile, err)
	}
	fmt.Printf("wrote %d tools to %s\n", len(infos), outputFile)
	return nil
}

// listTools boots the MCP server in-memory and returns its registered tools.
func listTools(ctx context.Context, cfg toolconfig.Config) ([]*mcp.Tool, error) {
	server := mcp.NewServer(&mcp.Implementation{Name: "rancher mcp server", Version: "doc-gen"}, nil)
	// A nil client is safe here: tool handlers are never invoked, only listed.
	toolsets.AddAllTools(nil, server, cfg)

	clientTransport, serverTransport := mcp.NewInMemoryTransports()

	serverSession, err := server.Connect(ctx, serverTransport, nil)
	if err != nil {
		return nil, fmt.Errorf("connecting server: %w", err)
	}
	defer serverSession.Close()

	client := mcp.NewClient(&mcp.Implementation{Name: "toolsdoc", Version: "doc-gen"}, nil)
	clientSession, err := client.Connect(ctx, clientTransport, nil)
	if err != nil {
		return nil, fmt.Errorf("connecting client: %w", err)
	}
	defer clientSession.Close()

	var tools []*mcp.Tool
	for tool, err := range clientSession.Tools(ctx, nil) {
		if err != nil {
			return nil, fmt.Errorf("iterating tools: %w", err)
		}
		tools = append(tools, tool)
	}
	return tools, nil
}

// toolsetOf returns the toolset annotation for a tool, or "other" if unset.
func toolsetOf(t *mcp.Tool) string {
	if ts, ok := t.Meta["toolset"].(string); ok && ts != "" {
		return ts
	}
	return "other"
}

// render produces the Markdown document for the given tools.
func render(infos []toolInfo) string {
	byToolset := map[string][]toolInfo{}
	for _, info := range infos {
		byToolset[info.toolset] = append(byToolset[info.toolset], info)
	}

	toolsetNames := make([]string, 0, len(byToolset))
	for name := range byToolset {
		toolsetNames = append(toolsetNames, name)
	}
	sort.Strings(toolsetNames)

	var b strings.Builder
	b.WriteString("# Available Tools\n\n")
	b.WriteString("<!-- Code generated by `go generate ./...`. DO NOT EDIT. -->\n")
	b.WriteString("<!-- Edit the tool definitions in pkg/toolsets/**/tools.go and regenerate. -->\n\n")
	b.WriteString("Each tool is exposed through the MCP protocol and can be invoked by the Rancher AI agent. ")
	b.WriteString("Tools are grouped by toolset. Tools marked **Write** modify state and are only registered when the server is not running in read-only mode.\n\n")

	for _, name := range toolsetNames {
		tools := byToolset[name]
		sort.Slice(tools, func(i, j int) bool { return tools[i].name < tools[j].name })

		fmt.Fprintf(&b, "## %s\n\n", name)
		b.WriteString("| Tool | Access | Description |\n")
		b.WriteString("|------|--------|-------------|\n")
		for _, t := range tools {
			access := "Read-only"
			if t.write {
				access = "Write"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", t.name, access, mdCell(t.description))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// mdCell escapes a description for use inside a Markdown table cell.
func mdCell(s string) string {
	lines := strings.Split(strings.TrimSpace(s), "\n")
	for i, line := range lines {
		lines[i] = strings.TrimSpace(line)
	}
	s = strings.Join(lines, "<br>")
	s = strings.ReplaceAll(s, "|", "\\|")
	return s
}
